service:
  name: ts-todoapp-on-serverless

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1

functions:
  app:
    handler: server/index.handler
    events:
      - http:
          method: GET
          path: /
