service:
  name: ts-todoapp-on-serverless
custom: ${file(variables-for-serverless/db-variables.yml)}
plugins:
  - serverless-plugin-typescript
  - serverless-offline
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
functions:
  app:
    handler: server/index.handler
    events:
      - http:
          method: GET
          path: /
resources:
  # referred from https://s3.amazonaws.com/cloudformation-templates-us-east-1/Drupal_Single_Instance_With_RDS.template
  Resources:
    DBInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: 'ServerlessTodos'
        DBInstanceClass: 'db.t2.micro'
        MasterUsername: ${self:custom.DB.USER_NAME}
        MasterUserPassword: ${self:custom.DB.PASSWORD}
        AllocatedStorage: '5'
        Engine: MySQL
        EngineVersion: '5.7.19'
